#!/usr/bin/env ruby

require 'tempfile'

tmp_path    = File.expand_path("../../", __FILE__)
readme_path = File.expand_path("../../README.md", __FILE__)
index_path  = File.expand_path("../../docs/index.html", __FILE__)

ribbon = %{
<a href="https://github.com/johnsusi/bluesky">
    <img style="position: absolute; top: 0; left: 0; border: 0;"
         src="https://camo.githubusercontent.com/121cd7cbdc3e4855075ea8b558508b91ac463ac2/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f677265656e5f3030373230302e706e67"
         alt="Fork me on GitHub"
         data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_green_007200.png">
</a>
}

lines = File.open(readme_path).read.split(/\r?\n/)
lines.insert(2, ribbon)

file = Tempfile.new(['README', '.md'], tmp_path)
file.sync = true
puts file.path

file.write(lines.join("\n"))
file.write("\n")
file.rewind
system("spec-md #{file.path} > #{index_path}")

system("git commit #{index_path} -m 'Updated docs'")

# file.close
